# Generated by Django 4.0.1 on 2022-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notetext',
            field=models.CharField(max_length=100),
        ),
    ]
